name: nct_util
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - image: erlang:22
          - image: erlang:23
          - image: erlang:24
    runs-on: self-hosted
    container:
      image: ${{ matrix.image }}
      options: "--entrypoint /bin/bash"

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v2
      - uses: nomasystems/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Inspect rebar3 version
      - name: Rebar version
        run: rebar3 --version

      # PRE Checks
      - name: Checks
        run: rebar3 check

      # Compile
      - name: Compile
        run: rebar3 compile